from math import *
num1 = input("Enter The 1st Number ? ")
num2 = input("Enter The 2nd Number ? ")
Result = int(num1) + int(num2)
num3 = input("Enter The 3rd Number ? ")
num4 = input("Enter The 4th Number ? ")
Answer = float(num3)+float(num4)
print("Result: " + str(Answer))
print("------------------------------")
print("        MAD LIB GAME          ")
print("=-=-=-=-=-=-=-=-=-=-=-=-=-=-==")
color = input("Please enter the color ? ")
print("Roses are "+color)
p_noun = input("Please enter the color ? ")
print(p_noun + " are blue")
celeb = input("Please enter the color ? ")
print("I love " + celeb)
print("*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")
story = (input("Please create a 1 line story of about 9/10 words: \n"))
print("Story: "+story)
s_color = story.index(",")
s_noun = story.index(" ")
s_celeb = story.index(".")
print("Color: "+str(s_color)+"\nNoun: "+str(s_noun)+"\nCeleb: "+str(s_celeb))
